#!/usr/bin/env ruby -w

require 'fileutils'

# Verify the following file locations before running
slack_files = [
  '/Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js',
  '/Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/index.js'
]
# This file location is very specific to my system
# Change the next line to wherever you saved the dark theme JS code
theme_file = "#{ENV['DOTFILES']}/templates/custom_dark_slack_theme.js"

# Make sure files exist
(slack_files << theme_file).each do |file|
  exists = File.exist?(file)
  unless exists
    puts "File does not exist: #{file}"
    exit
  end
end

# Open target and source files and get content
source_lines = File.open(theme_file).readlines

skipped = 0
slack_files.each do |file|
  # Change ownership (if necessary) so script can write to file
  # This will prompt you to enter your system password
  original_user = Etc.getpwuid(File.stat(file).uid).name
  original_group = Etc.getgrgid(File.stat(file).gid).name
  user = `whoami`.chomp

  needs_chowned = user != original_user
  `sudo chown #{user}:staff #{file}` if needs_chowned

  target_file = File.open(file, 'a+')
  target_lines = target_file.readlines

  # Check if custom theme has already been added
  if target_lines.last == source_lines.last
    skipped += 1
    puts "Theme already added"
    next
  else
    # Add new line between original code and custom theme code
    # then write custom theme code to slack file
    target_file.puts
    source_lines.each { |line| target_file.print line }
    puts "Theme added to #{file}"
  end

  # Change ownership back if necessary
  `sudo chown #{original_user}:#{original_group} #{file}` if needs_chowned
end

$stdout.puts "Theme updated from #{theme_file}" unless skipped == slack_files.length
exit
