#! /usr/bin/env ruby -w

def usage(err = nil)
  puts err if err
  puts if err
  puts "Usage:"
  puts "\tfor_file_in_dir DIR 'Ruby code string using `file` as the local variable name'"
  puts "\t Flags:"
  puts "\t\t-h --help help   This usage message"
  puts "\t\t-d --allow-dirs  Will process dirs as files (does not do this by default)"
  puts
  puts "Examples:"
  puts "\tfor_file_in_dir 'f = File.open(file, \"a+\"); f.puts \"Hello World\"'"
  puts "\tfor_file_in_dir ~/.dotfiles 'puts file'"
end

def flags_passed_in?(flags_arr, num_args = nil)
  num_args ||= ARGV.length
  (ARGV - flags_arr).length != num_args
end

# Main
if flags_passed_in? %w(-h --h --help help)
  usage
  exit
end

allow_dirs = false
allow_dirs_flags = %w(-d --allow-dirs)
if flags_passed_in? allow_dirs_flags
  allow_dirs = true
  allow_dirs_flags.each { |flag| ARGV.delete flag }
end

if ARGV.length == 2
  dir = ARGV[0]
  code_str =ARGV[1]
elsif ARGV.length == 1
  dir = './'
  code_str = ARGV[0]
else
  err = ArgumentError.new "ArgumentError: Wrong number of arguments: expected 1 or 2, received #{ARGV.length}"
  puts usage(err)
  exit
end

prc = Proc.new { |file| eval(code_str) }

files = Dir.glob("#{dir}/*", File::FNM_DOTMATCH)[2..-1] || []
files.each do |file|
  next unless allow_dirs || File.file?(file)
  prc.call(file)
end
