#! /usr/bin/env ruby -w

def usage(err = nil)
  puts err if err
  puts if err
  puts "Usage:"
  puts "\tfor_file_in_dir DIR 'Ruby code string using `file` as the local variable name'"
  puts
  puts "Examples:"
  puts "\tfor_file_in_dir 'f = File.open(file, \"a+\"); f.puts \"Hello World\"'"
  puts "\tfor_file_in_dir ~/.dotfiles 'puts file'"
end

# Main
num_args = ARGV.length

if (ARGV - %w(-h --h --help help)).length != num_args
  usage
  exit
end

if num_args == 2
  dir = ARGV[0]
  code_str =ARGV[1]
elsif num_args == 1
  dir = './'
  code_str = ARGV[0]
else
  err = ArgumentError.new "ArgumentError: Wrong number of arguments: expected 1 or 2, received #{num_args}"
  puts usage(err)
  exit
end

prc = Proc.new { |file| eval(code_str) }

files = Dir.glob("#{dir}/*", File::FNM_DOTMATCH)[2..-1] || []
files.each do |file|
  next unless File.file?(file)
  prc.call(file)
end
