#! /usr/bin/env ruby -w

def usage(err)
  puts err
  puts
  puts "Usage:"
  puts "\tfor_file_in_dir DIR 'Ruby code string using `file` as the local variable name'"
  puts
  puts "Examples:"
  puts "\tfor_file_in_dir 'f = File.open(file, \"a+\"); f.puts \"Hello World\"'"
  puts "\tfor_file_in_dir ~/.dotfiles 'puts file'"
end

def run
  num_args = ARGV.length

  if num_args == 0
    err = ArgumentError.new "ArgumentError: Too few arguments: expected 1 or 2, reveived #{num_args}"
    puts usage(err)
    exit
  elsif num_args == 2
    dir = ARGV[0]
    code_str =ARGV[1]
  elsif num_args == 1
    dir = './'
    code_str = ARGV[0]
  else
    err = ArgumentError.new "ArgumentError: Too many arguments: expected 1 or 2, reveived #{num_args}"
    puts usage(err)
    exit
  end

  prc = Proc.new { |file| eval(code_str) }

  files = `ls -A #{dir}`.split("\n")
  files.each(&prc)
end

run
