#! /usr/bin/env zsh

. $DOTFILES/.functions

full_pid=$(lsof -nP -iTCP:$1 | grep LISTEN)
pid=$(echo "$full_pid" | awk '{print $2}')

if [[ "$pid" = '' ]]
then
  echo "No processes found on port $1"
  exit 1
fi

echo "FOUND: $full_pid"
die $pid
