#!/usr/bin/env ruby -w

################
# Dependencies #
################
begin
  verbose = $VERBOSE
  $VERBOSE = nil # Suppress deprecation warnings and the like

  require 'optparse'
  require_relative '../lib/rb/cli_utils'
  # add more requires here
rescue LoadError => err
  # Error example:
  #   pry(main)> require 'fake_gem/with/path'
  #   LoadError: cannot load such file -- fake-gem/with/path
  #   from /Users/username/.rbenv/versions/2.4.7/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  dependency = err.message.split(' -- ').last
  # Remove '/with/path' from the gem name; noop for all others
  dependency = dependency.split('/').first
  warn "Missing dependency: #{dependency}"
  warn 'Make sure the following command completes successfully before using this script.'
  warn "\tgem install #{dependency}"
  exit 1
ensure
  $VERBOSE = verbose
end

#############
# Ruby code #
#############

def copy_template(type)
  case type
  when 'jira-qa'
    jira_qa_template
  else
    raise "Unknown template type: #{type}"
  end
end

def jira_qa_template
  <<~TEMPLATE
    h2. Local dev QA

    h3. Scenario N
    {{ncj}}

    {color:purple}Notes{color}
  TEMPLATE
end

################
# Shell script #
################
if $PROGRAM_NAME == __FILE__
  # options = {}
  # OptionParser.new do |opts|
  #   opts.on('-v', '--verbose', 'More loquacious') do
  #     options[:verbose] = true
  #   end

  #   # opts.on('-oVAL', '--option-with-value=VAL', 'Option with value message') do |val|
  #   #   options[:value] = val
  #   # end

  #   opts.on_tail('-h', '--help', 'Show this help message') do
  #     puts opts
  #     exit
  #   end
  # end.parse!

  if ARGV.empty?
    puts 'No arguments provided. Please provide a template type.'
    exit 1
  end

  template_type = ARGV[0]
  template = copy_template(template_type)
  IO.popen('pbcopy', 'w') { |f| f << template }
  $stdout.puts "#{template}\n^^^ copied to clipboard"
end
