#!/usr/bin/env ruby -w

########
# WIP! #
########

# function pids_for {
#   psaux_with_grep $1 |
#   grep -v grep |
#   awk '{print $2}' |
#   tr '\n' ' ' |
#   sed 's/[[:space:]]*$//'
# }

# TODO: make sure to only search commands
# not the path to the command
# and not the flags passed with the command
require 'pry'

pattern = ARGV.pop
puts pattern
verbose = ARGV[0] == '-v'
puts verbose
cmd = "ps aux | grep #{pattern}"
$stdout.puts(verbose ? `#{cmd}` : `parse_ps_aux $(#{cmd})`)
# This is not currently in use: see pids_for in `.functions`
