#!/usr/bin/env ruby -w

########
# WIP! #
########

# function pids_for {
#   psaux_with_grep $1 |
#   grep -v grep |
#   awk '{print $2}' |
#   tr '\n' ' ' |
#   sed 's/[[:space:]]*$//'
# }

# TODO: make sure to only search commands
# not the path to the command
# and not the flags passed with the command

pattern = ARGV[0]
puts `parse_ps_aux $(ps aux | grep #{pattern})`
