#!/usr/bin/env ruby -w

begin
  require 'colorize'
rescue LoadError => err
  dependency = err.message.split(" -- ").last
  begin
    $stderr.puts "Attempting to install #{dependency}"
    `gem install #{dependency}`
  rescue StandardError => err
    $stderr.puts "Error attempting to install #{dependency}"
    $stderr.puts err
    $stderr.puts "Git Branch History is missing a dependency: #{dependency}\nMake sure the following command completes successfully before using this script.\n\tgem install #{dependency}"
    exit
  end
end

#########
# SETUP #
#########
class GitBranchHistory
  class NotGitRepoError < StandardError; end

  DIR_NAME = "#{ENV['HOME']}/.git_branch_history".freeze

  def initialize(args:)
    @file_name = `2> /dev/null git rev-parse --show-toplevel`.chomp.split('/')[-1]
    raise NotGitRepoError, "#{Dir.pwd} is not a git repository" if @file_name&.include?("Not a git repository")

    @args = args
    @file_path = "#{DIR_NAME}/#{@file_name}"
    `mkdir #{DIR_NAME}` unless Dir.exist? DIR_NAME
    `touch "#{@file_path}"`
  end

  def usage
    $stdout.puts "USAGE: git_branch_history CMD [ARGS]"
    $stdout.puts "CMDs:  add|current|csv|delete|get|help|last|list|ls|push|remove|rm|set|open\n\n"
    $stdout.puts "       push|set|add: add branch to history"
    $stdout.puts "                     ARGS: branch_name (default: current branch)\n\n"
    $stdout.puts "      last|prev|get: get last (n) branch(es)"
    $stdout.puts "                     ARGS: number_of_branches_to_retrieve (default: 1)\n\n"
    $stdout.puts "            ls|list: list all branches (optionally that match a grep)"
    $stdout.puts "                     ARGS: (optional) string to grep\n\n"
    $stdout.puts "                csv: list all branches, comma-separated (optionally that match a grep)"
    $stdout.puts "                     ARGS: (optional) string to grep\n\n"
    $stdout.puts "\trm|remove|delete:  delete specified branch from history"
    $stdout.puts "                     ARGS: branch_name (required)\n\n"
    $stdout.puts "               help: Print this message"
    $stdout.puts "               open: Open the branch history file"
  end

  def add_branch!
    branch = @args.shift || current_branch
    branches_arr.delete branch # Ensure no duplicates added
    branch == current_branch ? branches_arr << branch : branches_arr.unshift(branch)
    update_file!
  end

  def branches_arr
    unless File.file? @file_path
      if @file_path == "#{DIR_NAME}/"
        $stderr.puts "WARN: This does not appear to be a git repo.".yellow
      else
        $stderr.puts "WARN: #{@file_path} is not a file.".yellow
      end
      exit
    end
    @branches ||= begin
      file = File.open(@file_path.to_s, "r+")
      branches = file.readlines.map(&:strip).compact
      file.close
      branches
    end
    @branches
  end

  def current_branch
    @current_branch ||= `git symbolic-ref -q HEAD`.strip.gsub("refs/heads/", "")
  end

  def current_branch_pretty
    "#{current_branch} (current)".cyan
  end

  def prev_branch
    branches = branches_arr.dup
    branches.delete current_branch
    n = (@args.shift || 1).to_i

    return current_branch_pretty if branches.length.zero?
    return branches if branches.length < n

    branches[-n..-1]
  end

  def list_branches(cmd)
    branches = branches_arr.dup
    grep = @args.shift
    branches.select! { |branch| branch.match(/#{grep}/).nil? } unless grep.nil?
    return branches.join(", ") if cmd == "csv"

    branches.map! do |branch|
      current_branch == branch ? "#{branch} (current)".cyan : branch
    end
  end

  def remove_branch!
    str = @args.shift
    old_branches = branches_arr.dup
    branches_arr.reject! { |branch| branch.include?(str) }
    deleted_branches = old_branches - branches_arr
    $stdout.puts "Deleted branches:\n\t#{deleted_branches.join("\n\t")}"
    update_file!
  end

  def update_file!
    file = File.open(@file_path.to_s, "w+")
    branches_arr.each do |branch|
      next if branch.empty?

      file.puts branch
    end
    file.close
  end

  def main
    if @args.length.zero? || @args[0] == "help"
      usage
      return
    end

    cmd = @args.shift

    case cmd
    when "push", "set", "add"
      add_branch!
    when "last", "get", "prev"
      $stdout.puts prev_branch
    when "list", "all", "csv", "ls"
      $stdout.puts list_branches(cmd)
    when "remove", "delete", "rm"
      if @args.empty?
        $stdout.puts "Must specify a branch to remove"
        return
      end
      remove_branch!
    when "current"
      $stdout.puts current_branch
    when "open"
      $stdout.puts "Attempting to open #{@file_path}"
      if !`which code`.empty?
        $stdout.puts "Trying VS Code"
        `code #{@file_path}`
      elsif !`which atom`.empty?
        $stdout.puts "Trying Atom"
        `atom #{@file_path}`
      elsif !`which subl`.empty?
        $stdout.puts "Trying Sublime"
        `subl #{@file_path}`
      else
        $stdout.puts "Couldn't find VS Code, Atom, or Sublime"
        $stdout.puts "Open with Vim? [y/n]"
        use_vim = $stdin.gets.chomp.downcase
        use_vim == 'y' ? `vim #{@file_path} < $(tty) > $(tty)` : "Could not open #{@file_path}"
      end
    else
      usage
    end
  end
end

begin
  tracker = GitBranchHistory.new args: ARGV
  tracker.main
rescue GitBranchHistory::NotGitRepoError => e
  warn e
  exit 1
end
