#!/usr/bin/env ruby -w

def usage
  $stdout.puts "Usage: `git_push_set_upstream [-h, --help] [[REMOTE] BRANCH]`"
end

if ARGV[0]&.include?("-h")
  usage
  exit
end

remote = branch = nil
args = ARGV.select { |el| !el.start_with?('--') }
flags = ARGV.select { |el| el.start_with?('--') }.join(' ')

case args.length
when 2
  remote = args.shift
  branch = args.shift
when 1
  branch = args.shift
end

remote ||= "origin"
branch ||= `git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3`

$stdout.puts("Flags: #{flags}\nRemote: #{remote}\nBranch: #{branch}")

`git push #{flags} --set-upstream #{remote} #{branch}`
