#!/usr/bin/env ruby -w

def usage
  $stdout.puts "Usage: `git_push_set_upstream [-h, --help] [[REMOTE] BRANCH]`"
end

if ARGV[0]&.include?("-h")
  usage
  exit
end

remote = branch = nil

case ARGV.length
when 2
  remote = ARGV[0]
  branch = ARGV[1]
when 1
  branch = ARGV[0]
end

remote ||= "origin"
branch ||= `git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3`

`git push --set-upstream #{remote} #{branch}`
