#!/usr/bin/env ruby -w

unless ARGV.length > 1
 $stdout.puts "Must provide 2 or 3 args\n\tSTRING PATTERN [REPLACEMENT]\n\tDefault replacement: ''"
  exit
end

string = ARGV.shift
pattern, replacement = ARGV
pattern = Regexp.new(pattern.gsub("/", "")) if pattern.start_with? "/"
replacement ||= ""
$stdout.puts string.gsub(pattern, replacement)
