#!/usr/bin/env ruby -w

# Color-wrapper for the standard shell `diff` command

require "colorize"

output_str = `diff #{ARGV.join(" ")}`
output_arr = output_str.split("\n")

output_arr.each do |line|
  color = line[0] == ">" ?
    :green :
    line[0] == "<" ?
      :red :
      ""
  $stdout.puts line.colorize color
end
