#!/usr/bin/env bash

source $DOTFILES/.aliases &1>/dev/null

mkdir -p "~/.netd"
filename="$HOME/.netd/fulldiagnostic-$(date +%s)"

echo "localip:\n\t$(localip)" >> $filename
echo "\n" >> $filename
echo "remoteip:\n\t$(remoteip)" >> $filename
echo "\n" >> $filename
echo "arp -na:\n$(arp -na)" >> $filename
echo "\n" >> $filename
echo "ifconfig:\n$(ifconfig)" >> $filename
echo "\n" >> $filename
