#!/usr/bin/env bash

mkdir -p "$HOME/.netd"
filename="$HOME/.netd/fulldiagnostic-$(date +%s)"

touch $filename
echo "localip:\n\t$(localip)" >> $filename
echo "\n" >> $filename
echo "remoteip:\n\t$(remoteip)" >> $filename
echo "\n" >> $filename
echo "arp -na:\n$(arp -na)" >> $filename
echo "\n" >> $filename
echo "ifconfig:\n$(ifconfig)" >> $filename
echo "\n" >> $filename
echo "open ports:\n$(port_checker_remote `localip`)" >> $filename
echo "\n" >> $filename
