#! /usr/bin/env zsh

# Note: this script is aliased as `on_port` in .aliases-post-scripts

if [ "$1" = "pid" ]
then
  pid_only=1
  shift
fi

if [ ! $1 ]; then
  path="$0"
  prefix=~/.dotfiles/scripts/
  name=${path#"$prefix"}
  echo "$RED""ArgumentError:$NONE expected 1 or more PORT arguments but got none"
  echo "\tUsage: $name [pid] PORT [PORTs ...]"
  exit 1
fi

# Catch non-numerical port arg
num_re='^[0-9]+$'

for port in "$@"; do
  if [ ! $pid_only ]; then
    printf "$PPL""Checking port: $YLW$port\t\t$NONE"
  fi

  if [[ ! "$port" =~ "$num_re" ]]
  then
    echo "$RED""ArgumentError:$NONE Port '$port' is not a number :/"
    exit 3
  fi

  # Check for open port
  local line=$(lsof -nPi :$port | grep LISTEN)
  if [[ ! "$line" && ! $pid_only ]]; then
    echo "\n$CYN""Nothing found on port $port$NONE" 1>&2
  # Successful response
  elif [[ $line && $pid_only ]]; then
    echo "$line" | awk '{print $2}' | tr ' ' '\n' | sort -u # | tr '\n' ' '
  elif [[ $line ]]; then
    echo "\n$line"
  fi
done

exit 0
