#! /usr/bin/env bash

if [ ! $1 ] || [ $# -gt 2 ]; then
  echo "ArgumentError: expected 1 or 2 arguments but got $#"
  echo "\tUsage: $0 [pid] PORT "
  exit 1
fi

if [ $2 ]; then
  port=$2
  pid=1 # Not a typo; this val just needs to be truthy
else
  port=$1
fi

line=$(lsof -nP -iTCP:$port | grep LISTEN)

if [ $pid ]; then
  echo $line | awk '{print $2}'
  exit 0
fi

echo $line
