#! /usr/bin/env zsh

# Note: this script is aliased as `on_port` in .aliases-post-scripts

pid_only=0

if [[ ${1-} == "pid" ]]; then
  pid_only=1
  shift
fi

if [[ -z ${1-} ]]; then
  path="$0"
  prefix=~/.dotfiles/scripts/
  name=${path#"$prefix"}
  echo "$RED""ArgumentError:$NONE expected 1 or more PORT arguments but got none" >&2
  echo "\tUsage: $name [pid] PORT [PORTs ...]" >&2
  exit 1
fi

# Catch non-numerical port arg
num_re='^[0-9]+$'

for port in "$@"; do
  if (( ! pid_only )); then
    printf "$PPL""Checking port: $YLW$port\t\t$NONE"
  fi

  if [[ ! "$port" =~ $num_re ]]; then
    echo "$RED""ArgumentError:$NONE Port '$port' is not a number :/" >&2
    exit 3
  fi

  # Check for open port
  # if pid_only, use -t flag, otherwise don't
  if (( pid_only )); then
    line=$(command lsof -tnPi :$port 2>/dev/null)
  else
    line=$(command lsof -nPi :$port 2>/dev/null | command grep LISTEN)
  fi

  if [[ -z "$line" ]]; then
    if (( ! pid_only )); then
      printf '\n%s\n' "$CYN""Nothing found on port $port$NONE" >&2
    fi
    continue
  fi

  if (( pid_only )); then
    printf '%s\n' "$line"
  else
    printf '\n%s\n' "$line"
  fi
done

exit 0
