#! /usr/bin/env bash

if [ ! $1 ] || [ $# -gt 2 ]; then
  echo "ArgumentError: expected 1 or 2 arguments but got $#"
  echo "\tUsage: $0 [pid] PORT "
  exit 1
fi

if [ $2 ]; then
  port=$2
  if [ $1 = "pid" ]
  then
    pid_only=1
  else
    # Catch invalid arg
    echo "ArgumentError: invalid arg: $1" && exit 2
  fi
else
  port=$1
fi

# Catch non-numerical port arg
num_re='^[0-9]+$'
if [ ! "$port" =~ "$num_re" ]
then
  echo "Port '$port' is not a number :("
  exit 3
fi

line=$(lsof -nP -iTCP:$port | grep LISTEN)

#
if [ ! $line ]
then
  echo "$RED""Nothing found on port $port$NONE" 1>&2
  exit 4
fi

# Successful responses
if [ $pid_only ]; then
  echo $line | awk '{print $2}'
  exit
fi

echo $line
