#!/usr/bin/env ruby -w

########
# WIP! #
########

skip_these = ['.', '..', '.DS_Store']
do_not_unmount = ['MobileBackups', 'Macintosh HD']

unmount_flags = ['--unmount', '-u']
unmount = ARGV.any? { |arg| unmount_flags.include?(arg) }

Dir.foreach('/Volumes') do |file|
  next if skip_these.include?(file)
  $stdout.puts file
  next if file == do_not_unmount.include?(file)
  `sudo rm -r "#{file}"`
  $stdout.puts "#{file} removed"
end
