#!/usr/bin/env ruby -w

url_map = {
  basic: {
    default: "http://localhost:5000",
    apply: "http://localhost:5000/apply",
    logout: "http://localhost:5000/logout",
  },
  confluence: {
    default: "https://amount.atlassian.net/wiki/spaces/FSTK/overview",
  },
  fooda: {
    default: "https://app.fooda.com/settings/orders"
  }
  invision: {
    default: "https://avant.invisionapp.com/d/main#/projects",
    eloan: "https://avant.invisionapp.com/d/main#/projects/prototypes/10367137",
    hsbc: "https://avant.invisionapp.com/d/main/#/projects/prototypes/14017808",
    pnc: "https://avant.invisionapp.com/share/UWM47RBYZ52#/",
    regions: "https://avant.invisionapp.com/d/main#/projects/prototypes/11921519",
    synovus: "https://avant.invisionapp.com/d/main#/projects/prototypes/16091708",
    td: "https://avant.invisionapp.com/d/main#/projects/prototypes/11504423",
  },
  jenkins: {
    apply: {
      prod: "https://jenkins.ad.avant.com/job/s3_deploys/job/prod/job/avant-apply/build?delay=0sec",
      dev: "https://jenkins.ad.avant.com/job/s3_deploys/job/dev/job/avant-apply/build?delay=0sec",
    },
    default: "https://jenkins.ad.avant.com",
  },
  jira: {
    default: "https://amount.atlassian.net/secure/RapidBoard.jspa?rapidView=448&assignee=5cc9ec3b63fbe710042bfa65",
  },
  slack: {
    emojis: {
      amount: "https://amount.slack.com/customize/emoji",
      default: "https://amount.slack.com/customize/emoji",
      mac: "https://midwestaccess.slack.com/customize/emoji",
    },
  },
}

resource = ARGV.shift
url = url_map[resource&.to_sym] || url_map

while ARGV.length > 0
  subresource = ARGV.shift
  url = url[subresource.to_sym]
end

url = url[:default] || url if url.is_a? Hash
`open -a 'Google Chrome' #{url}` if url.is_a? String
$stdout.puts url
